### ISSUE TITLE
Release as a library

### ISSUE THREAD

**Issue by hadim** [m3sv/PlainUPnP#13]
Would you consider releasing artifacts from this repo on Maven so others can use your app as an Android library for their own development?

**Comment by hadim** [comment]
Looks like I can use Jitpack: https://jitpack.io/#m3sv/PlainUPnP/

**Comment by hadim** [comment]
Looks like the build didnt work: https://jitpack.io/com/github/m3sv/PlainUPnP/7844ce0970/build.log

**Comment by hadim** [comment]
See https://github.com/m3sv/PlainUPnP/pull/14

**Comment by m3sv** [comment]
@hadim Hey, what exactly are you interested in related to the application? If all you need is UPnP functionality, then you're better off start digging into Cling. 

For now everything here is a mess, because the app itself is a refactoring of another old application. So don't expect stable API to follow, not in the near future at least, unfortunately.

**Comment by hadim** [comment]
Thanks for your response. Indeed I already switched to cling.
